### ISSUE TITLE
Não executa

### ISSUE THREAD

**Issue by alexandrevicenzi** [pythonprobr/pythonbirds#5]
Ao tentar executar o app do branch master ou diversao ocorrem os seguintes error:

```
D:\git\pythonbirds [diversao]> C:\Python34\python.exe .\python_birds.py
Traceback (most recent call last):
  File ".\python_birds.py", line 2, in <module>
    from atores import PassaroVermelho, PassaroAmarelo, Porco, Obstaculo
ImportError: cannot import name 'PassaroVermelho'
```

```
D:\git\pythonbirds [diversao]> C:\Python34\python.exe .\executor_de_testes.py
EEEEEEE..
======================================================================
ERROR: fases.brasil (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Python34\lib\unittest\case.py", line 577, in run
    testMethod()
  File "C:\Python34\lib\unittest\loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: fases.brasil
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python34\lib\unittest\loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "D:\git\pythonbirds\fases\brasil.py", line 9, in <module>
    from atores import PassaroAmarelo, PassaroVermelho, Obstaculo, Porco
ImportError: cannot import name 'PassaroAmarelo'


======================================================================
ERROR: fases.escudo_espartano (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Python34\lib\unittest\case.py", line 577, in run
    testMethod()
  File "C:\Python34\lib\unittest\loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: fases.escudo_espartano
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python34\lib\unittest\loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "D:\git\pythonbirds\fases\escudo_espartano.py", line 10, in <module>
    from atores import PassaroAmarelo, PassaroVermelho, Obstaculo, Porco
ImportError: cannot import name 'PassaroAmarelo'


======================================================================
ERROR: fases.rodar_fase_exemplo (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Python34\lib\unittest\case.py", line 577, in run
    testMethod()
  File "C:\Python34\lib\unittest\loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: fases.rodar_fase_exemplo
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python34\lib\unittest\loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "D:\git\pythonbirds\fases\rodar_fase_exemplo.py", line 9, in <module>
    from atores import PassaroAmarelo, PassaroVermelho, Obstaculo, Porco
ImportError: cannot import name 'PassaroAmarelo'


======================================================================
ERROR: placa_grafica_tkinter (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Python34\lib\unittest\case.py", line 577, in run
    testMethod()
  File "C:\Python34\lib\unittest\loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: placa_grafica_tkinter
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python34\lib\unittest\loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "D:\git\pythonbirds\placa_grafica_tkinter.py", line 9, in <module>
    from fase import Fase
ImportError: cannot import name 'Fase'


======================================================================
ERROR: python_birds (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Python34\lib\unittest\case.py", line 577, in run
    testMethod()
  File "C:\Python34\lib\unittest\loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: python_birds
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python34\lib\unittest\loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "D:\git\pythonbirds\python_birds.py", line 2, in <module>
    from atores import PassaroVermelho, PassaroAmarelo, Porco, Obstaculo
ImportError: cannot import name 'PassaroVermelho'


======================================================================
ERROR: testes.atores_testes (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Python34\lib\unittest\case.py", line 577, in run
    testMethod()
  File "C:\Python34\lib\unittest\loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: testes.atores_testes
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python34\lib\unittest\loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "D:\git\pythonbirds\testes\atores_testes.py", line 5, in <module>
    from atores import Ator, DESTRUIDO, ATIVO, Obstaculo, Porco, PassaroAmarelo, PassaroVermelho
ImportError: cannot import name 'Ator'


======================================================================
ERROR: testes.fase_testes (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Python34\lib\unittest\case.py", line 577, in run
    testMethod()
  File "C:\Python34\lib\unittest\loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: testes.fase_testes
Traceback (most recent call last):
  File "C:\Python34\lib\unittest\loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python34\lib\unittest\loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "D:\git\pythonbirds\testes\fase_testes.py", line 13, in <module>
    from atores import Obstaculo, Porco, PassaroVermelho, PassaroAmarelo, DESTRUIDO, ATIVO
ImportError: cannot import name 'Obstaculo'


----------------------------------------------------------------------
Ran 9 tests in 0.016s

FAILED (errors=7)
D:\git\pythonbirds [diversao]>
```

**Comment by renzon** [comment]
Olá Alexandre. Primeiramente obrigado pelo interesse, ao ponto de escrever uma pendência aqui no Github. Contudo, o que aconteceu não é bug, é feature. Pela filosofia do projeto, as versões master e diversão não possuem implementação, cabendo ao aluno implementar o jogo baseado na documentação e testes automáticos.

Veja essa vídeo aula que talvez fique claro:

https://www.youtube.com/watch?v=gRXa13c_ADc&index=6&list=PLA05yVJtRWYTm0sIa6n56UpCjCsR5ekla

Ou seja, se vc quer ver o jogo funcionando, experimente a branc simples-solucao ou stateless-solucao.

Grande abraço.
